### ISSUE TITLE
Cron jobs page not see process

### ISSUE THREAD

**Issue by sports23** [owsPro/OWS_for_All_PHP#2]
![Jobs](https://github.com/owsPro/OWS_for_All_PHP/assets/150643750/9dfacbac-0199-42a5-bfb9-4094133728f8)
Thank you in advance !!! U are the best, good jov anyway

**Comment by owsPro** [comment]
- Fixed: Cron jobs page not see

The internal execution has not been working properly for a very long time, since the servers only have a script runtime of 30 seconds instead of 5 minutes. Therefore, the jobs must be carried out in the administration of the web space and according to https://github.com/ihofmann/open-websoccer/wiki/15.-Setup-Cron-jobs.
