### ISSUE TITLE
NO PLAYERS SHOWING IN THE FRONT PAGE

### ISSUE THREAD

**Issue by sports23** [owsPro/OWS_for_All_PHP#7]
![NO PLAYERS IN FRONT](https://github.com/owsPro/OWS_for_All_PHP/assets/150643750/947abd8c-646e-4596-9f70-48e1991aa055)
![PLAYERS IN BACKOFFICE](https://github.com/owsPro/OWS_for_All_PHP/assets/150643750/537fa693-e01e-4c90-a75a-3c094dee952a)
In the backoffice i have it

**Comment by owsPro** [comment]
I have the players!
https://owspro.forallphp.eu/?page=team&id=12#players

**Comment by sports23** [comment]
![Screenshot_20231114-191605_Free Adblocker Browser](https://github.com/owsPro/OWS_for_All_PHP/assets/150643750/b985557b-8237-4cd4-a954-4f4d339682fd)

I have it to but în the backoffice

![Screenshot_20231114-191927_Free Adblocker Browser](https://github.com/owsPro/OWS_for_All_PHP/assets/150643750/dbbf1fc9-0b0c-46bb-858c-a7fca75f2046)

**Comment by sports23** [comment]
![NO PLAYERS IN FRONT2](https://github.com/owsPro/OWS_for_All_PHP/assets/150643750/6a2e2a96-ace3-4ce1-b5ad-f9a9c778acdc)
Like you see the time is fixt but no the front club players...

**Comment by owsPro** [comment]
Instead of 23, an additional 23 players were generated for this club. Due to the error, if you generate a squad for individual teams, these players are formally added to the team, but if you look in the admin centre under players, the players have not been given the club name.

This could cause the error. In my case, however, the 23 players are displayed, but the additional players are correctly not displayed.

So a fix is still open.

**Comment by sports23** [comment]
@owsPro #6 There is the solution for all those problem. Thank you for all your support! if i found something else... i will make a issue!
