### ISSUE TITLE
Where can i make change for the language format ?

### ISSUE THREAD

**Issue by sports23** [owsPro/OWS_for_All_PHP#8]
![BAD FORMAT Language](https://github.com/owsPro/OWS_for_All_PHP/assets/150643750/c1793b68-de55-4f6d-a062-b330a3cab1c3)

i wanna help in that

**Comment by owsPro** [comment]
So far 4 languages are included, the remaining languages are not yet translated, these languages have to be removed in the admin centre.

A copied language file for a country that you have translated yourself is not recommended, as otherwise your own translation will be overwritten during a translation update.

**Comment by sports23** [comment]
oh, ok... i understand! :)
